/* Raum 2 · Die Fossilienkammer · Missionen 2.1 bis 2.4 (Stand 05.10.2026, Fassung V1.1 nach Steckbriefen Raum 2 V2, Ammonit schrittweise)
   Diese Datei wird aus raum2.src.js erzeugt. Lösungen stehen in raum2.js nur als Hash.
   Bilder in raum2/bilder/*.svg sind gezeichnete Platzhalter (tools/make_platzhalter.py). Alle Daten zum Berolinavis sind fiktiv. */
TRESOR.room({
  base: '../',
  id: 'raum2',
  title: 'Die Fossilienkammer',
  subtitle: 'Raum 2 · Befunde als Evidenz',
  image: 'bilder/kammer.jpg',
  imageAlt: 'Eine nächtliche Sammlungskammer mit Schubladenschrank, Gesteinsprofil, Vitrine und Schreibtisch',
  size: [1200, 896],
  flashlight: true,
  unlockMode: 'auto',   /* 'auto' = ohne Code (Haken für das Do Now), 'code' = Lehrkraft nennt den Code */

  caseText: function (T) {
    var t = 'Dr. Johanna Wendt ist verschwunden. Der Händler Viktor Hallmann will den „Berolinavis“ versteigern.\n\nIn Dr. Wendts Fossilienkammer prüft ihr, was ein Fossil belegen kann. Ob der Berolinavis echt ist, wisst ihr noch nicht.';
    if (T.isSolved('r2-1-folge')) t += '\n\nIhr wisst: Ein Fossil ist erst mit seinem Fundkontext ein Befund.';
    if (T.isSolved('r2-2-tabelle')) t += '\n\nIhr habt drei Tiere nach einem festen Kriterium verglichen.';
    if (T.isSolved('r2-3-frage')) t += '\n\nVor jedem Brückentier steht die Frage: Gehören alle Teile zum selben Tier?';
    if (T.isSolved('r2-4-schloss')) t += '\n\nVier unabhängige Befunde sprechen dafür, dass der Berolinavis zusammengesetzt ist. Das ist ein starker Verdacht, noch kein Urteil.';
    return t;
  },

  end: { title: 'Raum 2 geschafft', text: 'Sichert jetzt euren Spielstand. Wie es weitergeht, erfahrt ihr in der nächsten Stunde.' },

  missions: [
    { id: 'm2.1', title: 'Mission 2.1 · Ein Fossil ist ein Befund', unlock: 'fc7dd5e6577602b3f3abe507d359da0ad382ff602162db6bb124b231b1d5ecdd',
      intro: { from: 'kemal', text: 'Das ist Dr. Wendts Fossilienkammer. Nehmt die Taschenlampe.\n\nHier lernt ihr, was ein Fossil überhaupt belegen kann. Fangt an der Profilwand an.',
        next: { from: 'wendt', text: 'Bevor ihr den Berolinavis untersucht, müsst ihr wissen, was ein Fossil überhaupt belegen kann. Ein Fund ist nur so viel wert wie das, was wir über seine Herkunft wissen.\n\n– J. W.' } },
      requires: ['r2-1-schichten', 'r2-1-tiefe', 'r2-1-aussagekraft', 'r2-1-zettel', 'r2-1-folge'],
      doneTitle: 'Mission 2.1 abgeschlossen',
      doneText: 'Ihr wisst jetzt, was ein Fossil belegen kann und was nicht.\n\nSchreibt eure Fundkontext-Karte und den Merksatz ins Logbuch.' },
    { id: 'm2.2', title: 'Mission 2.2 · Fossilvergleich', unlock: '9edf26ae39175c9a88fd7af0d041fb5cfabc18375be0a51a6b0b7e202f9256ec',
      intro: { from: 'kemal', text: 'Im Schrank liegen drei Vergleichsstücke. Bevor ihr sie anseht: Legt fest, wonach ihr vergleicht.' },
      requires: ['r2-2-kriterium', 'r2-2-vergleich', 'r2-2-tabelle'],
      doneTitle: 'Mission 2.2 abgeschlossen',
      doneText: 'Euer Vergleichsprotokoll liegt in der Akte. Ihr braucht es für den Urvogel.\n\nSchreibt jetzt den Merksatz ins Logbuch.' },
    { id: 'm2.3', title: 'Mission 2.3 · Merkmalsmosaik', unlock: 'c7cd1cda0d7d4bb9cb3537dee30787c1506f96a5c1b180ba00cdb46aae328606',
      intro: { from: 'wendt', text: 'Man nennt ihn ein Brückentier. Prüft, was das wirklich bedeutet.\n\n– J. W.' },
      requires: ['r2-3-mosaik', 'r2-3-deutung', 'r2-3-frage'],
      doneTitle: 'Mission 2.3 abgeschlossen',
      doneText: 'Ihr wisst jetzt, was ein Brückentier ist und was nicht. Und welche Frage vor allem anderen kommt.\n\nSchreibt jetzt eure Merkmalstabelle und den Merksatz ins Logbuch.' },
    { id: 'm2.4', title: 'Mission 2.4 · Der Berolinavis', unlock: 'f2a4d5e94375e26e440517b6b4a1e7d58396302eba817a9adc452c3f0d04e08a',
      intro: { from: 'kemal', text: 'Der Berolinavis liegt auf Dr. Wendts Arbeitstisch. Ihr kennt jetzt alle Werkzeuge.\n\nFangt mit seinem Fundzettel an.' },
      requires: ['r2-4-zettel', 'r2-4-linien', 'r2-4-ausreden', 'r2-4-schloss'],
      doneTitle: 'Mission 2.4 abgeschlossen · Schloss 2 geöffnet',
      doneText: 'Der Befund enthält Widersprüche in vier unabhängigen Linien. Das ist ein starker Verdacht, noch kein Urteil.\n\nSchreibt jetzt Aussage, Beleg und Reichweite in euer Logbuch.' }
  ],

  hotspots: [
    { id: 'gestein', label: 'Profilwand der Grube Nordhang', rect: [36, 15, 28.5, 33], states: [
      { if: { unlocked: 'm2.1', notSolved: 'r2-1-schichten' }, action: { type: 'puzzle', puzzle: 'r2-1-schichten' } },
      { if: { unlocked: 'm2.1', notSolved: 'r2-1-tiefe' }, action: { type: 'puzzle', puzzle: 'r2-1-tiefe' } },
      { if: { missionDone: 'm2.1', notSolved: 'r2-1-luecken' }, action: { type: 'puzzle', puzzle: 'r2-1-luecken' } },
      { if: { unlocked: 'm2.4' }, action: { type: 'doc', doc: 'grabungsprofil' } },
      { action: { type: 'doc', doc: 'profil' } } ] },
    { id: 'schrank', label: 'Sammlungsschrank mit Schubladen', rect: [1, 8, 27.5, 86], states: [
      { if: { unlocked: 'm2.1', solved: 'r2-1-tiefe', notSolved: 'r2-1-aussagekraft' }, action: { type: 'puzzle', puzzle: 'r2-1-aussagekraft' } },
      { if: { unlocked: 'm2.1', solved: 'r2-1-aussagekraft', notSolved: 'r2-1-zettel' }, action: { type: 'puzzle', puzzle: 'r2-1-zettel' } },
      { if: { unlocked: 'm2.1', solved: 'r2-1-zettel', notSolved: 'r2-1-folge' }, action: { type: 'puzzle', puzzle: 'r2-1-folge' } },
      { if: { unlocked: 'm2.2', notSolved: 'r2-2-kriterium' }, action: { type: 'puzzle', puzzle: 'r2-2-kriterium' } },
      { if: { unlocked: 'm2.2', notSolved: 'r2-2-vergleich' }, action: { type: 'puzzle', puzzle: 'r2-2-vergleich' } },
      { if: { unlocked: 'm2.2', notSolved: 'r2-2-tabelle' }, action: { type: 'puzzle', puzzle: 'r2-2-tabelle' } },
      { if: { missionDone: 'm2.2', notSolved: 'r2-2-passung' }, action: { type: 'puzzle', puzzle: 'r2-2-passung' } },
      { if: { solved: 'r2-2-kriterium' }, action: { type: 'docs', title: 'Fotokarten im Schrank', docs: ['fk-compsognathus', 'fk-archaeopteryx', 'fk-taube'] } },
      { action: { type: 'text', text: 'Die Schubladen sind verschlossen. Auf den Schildchen stehen Schichtnummern.' } } ] },
    { id: 'vitrine', label: 'Vitrine mit dem Urvogel', rect: [37.5, 49, 25.5, 41], states: [
      { if: { unlocked: 'm2.3', notSolved: 'r2-3-mosaik' }, action: { type: 'puzzle', puzzle: 'r2-3-mosaik' } },
      { if: { unlocked: 'm2.3', notSolved: 'r2-3-deutung' }, action: { type: 'puzzle', puzzle: 'r2-3-deutung' } },
      { if: { missionDone: 'm2.3', notSolved: 'r2-3-kein-brueckentier' }, action: { type: 'puzzle', puzzle: 'r2-3-kein-brueckentier' } },
      { if: { unlocked: 'm2.3' }, action: { type: 'image', title: 'Der Urvogel', image: 'bilder/urvogel.jpg', text: 'Ein Stein, eine Schicht, ein Tier.' } },
      { action: { type: 'text', text: 'Unter der Glashaube liegt ein Fossil. Die Haube ist noch verschlossen.' } } ] },
    { id: 'schreibtisch', label: 'Dr. Wendts Arbeitstisch', rect: [67, 72, 32, 23], states: [
      { if: { unlocked: 'm2.3', solved: 'r2-3-deutung', notSolved: 'r2-3-frage' }, action: { type: 'puzzle', puzzle: 'r2-3-frage' } },
      { if: { unlocked: 'm2.4', notSolved: 'r2-4-zettel' }, action: { type: 'puzzle', puzzle: 'r2-4-zettel' } },
      { if: { unlocked: 'm2.4', notSolved: 'r2-4-linien' }, action: { type: 'puzzle', puzzle: 'r2-4-linien' } },
      { if: { unlocked: 'm2.4', notSolved: 'r2-4-ausreden' }, action: { type: 'puzzle', puzzle: 'r2-4-ausreden' } },
      { if: { unlocked: 'm2.4', notSolved: 'r2-4-schloss' }, action: { type: 'puzzle', puzzle: 'r2-4-schloss' } },
      { if: { missionDone: 'm2.4', notSolved: 'r2-4-verwerfung' }, action: { type: 'puzzle', puzzle: 'r2-4-verwerfung' } },
      { action: { type: 'doc', doc: 'wendt-notiz' } } ] },
    { id: 'fenster', label: 'Fenster', rect: [77, 2, 23, 56], action: { type: 'text', text: 'Draußen liegt die Invalidenstraße im Mondlicht. Ein dunkles Auto fährt langsam vorbei … und hält kurz vor dem Museum. Dann fährt es weiter.' } }
  ],

  docs: {
    'wendt-notiz': { title: 'Dr. Wendts Notizbuch', style: 'notebook',
      text: 'Ein Fund ist nur so viel wert wie das, was wir über seine Herkunft wissen.\n\nImmer zuerst: Wo gefunden? In welcher Schicht? Passt das Gestein?\n\n– J. W.' },
    'profil': { title: 'Profilwand der Grube Nordhang', style: 'plaque', image: 'bilder/profilwand.svg',
      text: 'Schicht 1 (oben): heller, feinkörniger Plattenkalk\nSchicht 2: brauner Tonstein\nSchicht 3 (unten): dunkler, blättriger Tonschiefer\nDarunter: Grubensohle, nicht aufgeschlossen\n\nDie Schichten liegen ungestört.' },
    'pruefkarte': { title: 'Prüfkarte Fundkontext', style: 'paper',
      text: '1. Wo wurde es gefunden?\n2. In welcher Schicht, und passt sie zum Profil?\n3. Passt das Gestein zur Schicht?' },
    'fk-compsognathus': { title: 'Fotokarte: Compsognathus (kleiner Raubdinosaurier, gleiche Zeit)', style: 'paper', image: 'bilder/fotokarte-compsognathus.svg',
      text: 'Platzhalter. Im Unterricht vergleicht ihr echte Fossilien, Abgüsse oder Fotokarten.' },
    'fk-archaeopteryx': { title: 'Fotokarte: Archaeopteryx', style: 'paper', image: 'bilder/fotokarte-archaeopteryx.svg',
      text: 'Platzhalter. Im Unterricht vergleicht ihr echte Fossilien, Abgüsse oder Fotokarten.' },
    'fk-taube': { title: 'Fotokarte: Taube (heute), Skelett', style: 'paper', image: 'bilder/fotokarte-taube.svg',
      text: 'Platzhalter. Im Unterricht vergleicht ihr echte Fossilien, Abgüsse oder Fotokarten.' },
    'protokoll': { title: 'Vergleichsprotokoll', style: 'paper',
      text: '„Nicht nachgewiesen“ heißt bei einem Fossil: im Fund nicht erhalten oder nicht erkennbar. Bei der heutigen Taube heißt „nein“: fehlt wirklich.',
      table: { head: ['Merkmal', 'Compsognathus', 'Archaeopteryx', 'Taube'],
        rows: [['Zähne', 'ja', 'ja', 'nein'], ['Krallen an den Fingern', 'ja', 'ja', 'nein'], ['Lange knöcherne Schwanzwirbelsäule', 'ja', 'ja', 'nein'],
          ['Schwungfedern (Abdrücke)', 'nicht nachgewiesen', 'ja', 'ja'], ['Brustbeinkamm', 'nicht nachgewiesen', 'nicht nachgewiesen', 'ja']] } },
    'grabungsprofil': { title: 'Grabungsprofil Grube Nordhang (Abbauwand)', style: 'paper',
      text: 'Meter 0 bis 30: Schicht 1 ist abgetragen, oben liegt Schicht 2.\nAb Meter 30: Schicht 1 (heller Plattenkalk) über Schicht 2 und 3.\nGrubensohle: nicht aufgeschlossen.\n\nAngaben für das Spiel erfunden.' },
    'vergleichstiere': { title: 'Wirbelbreiten bei Vergleichstieren (Spieldaten)', style: 'paper',
      text: 'Verhältnis = Breite des letzten Beckenwirbels geteilt durch Breite des ersten Schwanzwirbels. Die Werte sind für das Spiel erfunden.',
      table: { head: ['Tier', 'Beckenwirbel', 'erster Schwanzwirbel', 'Verhältnis'],
        rows: [['V1', '5,1 mm', '5,2 mm', '0,98'], ['V2', '4,6 mm', '5,0 mm', '0,92'], ['V3', '6,0 mm', '5,7 mm', '1,05'], ['V4', '5,5 mm', '5,5 mm', '1,00'], ['V5', '4,9 mm', '5,1 mm', '0,96'], ['V6', '5,8 mm', '5,6 mm', '1,04']] } }
  },

  puzzles: {
    /* ---------------- Mission 2.1 ---------------- */
    'r2-1-schichten': { id: 'r2-1-schichten', type: 'order', title: 'Die Profilwand',
      ref: { title: 'Zum Nachschlagen: die Profilwand', docs: ['profil'] },
      prompt: 'Die Schichten an der Profilwand liegen ungestört. Ordnet die drei Funde vom ältesten zum jüngsten. Tippt sie in dieser Reihenfolge an.',
      items: [
        { id: 'fischsaurier', label: 'Fischsaurier', tag: 'gefunden in Schicht 3' },
        { id: 'ammonit', label: 'Ammonit', tag: 'gefunden in Schicht 2' },
        { id: 'urvogel', label: 'Urvogel', tag: 'gefunden in Schicht 1' }
      ],
      hash: '625c9d7eb622fd1f5731cf4538a4a73e4d39bc8b43ccc915f72c06fdd2b8685e',
      wrongText: 'Nichts passiert. Überlegt, wie die Schichten entstanden sind: Was wurde zuerst abgelagert?',
      hints: ['Schaut auf die Wand. Welche Schicht liegt unten, welche oben?',
              'Wenn sich Sediment ablagert, welches kommt zuerst, das untere oder das obere?',
              'Was unten liegt, ist älter. Der Fischsaurier liegt ganz unten, der Urvogel ganz oben.'],
      rescue: 'V2FzIHVudGVuIGxpZWd0LCB3dXJkZSB6dWVyc3QgYWJnZWxhZ2VydCB1bmQgaXN0IMOkbHRlcjogRmlzY2hzYXVyaWVyIChTY2hpY2h0IDMpLCBkYW5uIEFtbW9uaXQgKFNjaGljaHQgMiksIGRhbm4gVXJ2b2dlbCAoU2NoaWNodCAxKS4=',
      rescueTask: 'Erklärt in eigenen Worten, warum tiefer liegende Schichten älter sind, und nennt eine Bedingung, unter der das nicht gilt.',
      onSolve: { text: 'Die Fundkarten hängen jetzt in der richtigen Reihenfolge an der Wand.', then: 'r2-1-tiefe' } },

    'r2-1-tiefe': { id: 'r2-1-tiefe', type: 'select', title: 'Noch älter',
      prompt: 'Sagt vorher: Wo müsste ein Fossil liegen, das noch älter ist als der Fischsaurier? Tippt die Stelle an der Profilwand an.',
      image: 'bilder/profilwand.svg', imageAlt: 'Profilwand mit drei Schichten, darunter die Grubensohle, rechts eine Abraumhalde (Platzhalter)',
      marks: [
        { id: 's1', label: 'Schicht 1', x: 40, y: 21 },
        { id: 's2', label: 'Schicht 2', x: 40, y: 45 },
        { id: 's3', label: 'Schicht 3', x: 40, y: 67 },
        { id: 'sohle', label: 'Grubensohle', x: 62, y: 86 },
        { id: 'halde', label: 'Abraum', x: 88, y: 80 }
      ],
      hash: '205b24657f4aeabbfea166f092d700998da55196f73921582be73100b3a4ba40',
      wrongText: 'Nichts passiert. Was liegt unter dem Ältesten, das ihr kennt?',
      hints: ['Der Fischsaurier liegt in Schicht 3, ganz unten an der Wand.',
              'Was noch älter ist, wurde noch früher abgelagert. Wo liegt es dann?',
              'Ein noch älteres Fossil müsste noch tiefer liegen als Schicht 3.'],
      rescue: 'RWluIEZvc3NpbCwgZGFzIMOkbHRlciBpc3QgYWxzIGRlciBGaXNjaHNhdXJpZXIsIG3DvHNzdGUgdW50ZXIgU2NoaWNodCAzIGxpZWdlbiwgYWxzbyBpbiBkZXIgR3J1YmVuc29obGUu',
      rescueTask: 'Schreibt auf, warum ein älteres Fossil tiefer liegen müsste.',
      onSolve: { text: 'Die Profilwand leuchtet auf. Im Schrank klickt ein Schloss: Die Schubladen lassen sich öffnen.' } },

    'r2-1-aussagekraft': { id: 'r2-1-aussagekraft', type: 'objekt', mode: 'zeigen', title: 'Was der Ammonit belegt',
      prompt: 'Untersucht den Ammoniten. Zeigt bei jeder Aussage die Stelle, die sie belegt, oder wählt „Nicht erkennbar“. Streiflicht und Umdrehen helfen.',
      image: 'bilder/ammonit.svg', imageAlt: 'Ammonit auf einer Steinplatte (Platzhalter)',
      startText: 'Tippt auf die Stelle am Ammoniten, die diese Aussage belegt.',
      tools: [{ id: 'streif', label: 'Streiflicht', hint: 'Streiflicht von der Seite: Feine Linien auf dem Gehäuse werden deutlich.' }, { id: 'um', label: 'Umdrehen', hint: 'Die Rückseite des Stücks.' }],
      views: { streif: 'bilder/ammonit-streiflicht.svg', um: 'bilder/ammonit-rueckseite.svg' },
      spots: [
        { id: 'gehaeuse', label: 'Gehäuse', cat: 'stueck', tools: [null, 'streif'], x: 40, y: 36, w: 20, h: 28, text: 'Spiralig gewundenes Gehäuse, als Stein erhalten.' },
        { id: 'loben', label: 'Linien auf dem Gehäuse', cat: 'stueck', tools: [null, 'streif'], x: 30, y: 20, w: 16, h: 18, text: 'Verzweigte Linien: die Ansätze der Kammerwände. Im Streiflicht sieht man sie deutlich. So sind Ammoniten gebaut, Kopffüßer des Meeres.' },
        { id: 'bruch', label: 'Bruchkante', cat: 'stueck', tools: [null, 'streif'], x: 69, y: 30, w: 8, h: 26, text: 'Frische Bruchkante am Rand.' },
        { id: 'zettel', label: 'Fundzettel', cat: 'zettel', tool: 'um', x: 29, y: 28, w: 42, h: 44, text: 'Ein Zettel auf der Rückseite: „Ammonit · Grube Nordhang · Schicht 2 · brauner Tonstein · 1974“.' }
      ],
      rows: [
        { id: 'a1', label: 'Das Tier hat einmal gelebt.' },
        { id: 'a2', label: 'Es lebte im Meer.' },
        { id: 'a3', label: 'Es ist jünger als der Fischsaurier aus Schicht 3.' },
        { id: 'a4', label: 'Es ist 200 Millionen Jahre alt.' }
      ],
      noneLabel: 'Nicht erkennbar',
      parts: [{ id: 'stueck', label: 'Am Stück', hash: 'b8c7e6f7a8b33a063b47cd30025ed17f252aea9c6700d5b251beeadbe9874d4e' },
              { id: 'zettel', label: 'Auf dem Zettel', hash: 'c5d452603a539164fbd7f1f2e6f630185a9c276d3b6ffce4f9da792e2e977a39' },
              { id: 'nein', label: 'Nicht erkennbar', hash: '9f5464a45fdbaff6de12889b686ee1d8a53c2ea094a96f80704ae9647b772145' }],
      hash: '1bcaa8a8377f2bad4277804009f09c114db656ddcf072dc5cd78c5b67fce5dbb',
      button: 'Belege prüfen',
      wrongText: 'Nichts passiert. Fragt bei jeder Aussage: Woher wissen wir das?',
      hints: ['Prüft jede Aussage: Steht das im Stein, auf dem Zettel oder nirgends? Dreht das Stück auch einmal um.',
              'Aus der Lage in den Schichten folgt, ob etwas älter oder jünger ist. Folgt daraus auch eine genaue Zahl?',
              'Das Gehäuse zeigt, dass es gelebt hat, die Linien auf dem Gehäuse, dass es ein Meerestier war. Der Zettel zeigt: jünger als Schicht 3. Eine Zahl in Jahren zeigt nichts davon.'],
      rescue: 'RGFzIEdlaMOkdXNlIGJlbGVndCwgZGFzcyBkYXMgVGllciBnZWxlYnQgaGF0LiBEaWUgTGluaWVuIGF1ZiBkZW0gR2Vow6R1c2UgemVpZ2VuIGVpbmVuIEFtbW9uaXRlbiwgYWxzbyBlaW4gTWVlcmVzdGllci4gRGVyIEZ1bmR6ZXR0ZWwgbmVubnQgU2NoaWNodCAyOiBEZXIgQW1tb25pdCBpc3QgasO8bmdlciBhbHMgRnVuZGUgYXVzIFNjaGljaHQgMy4gRWluIEFsdGVyIGluIEphaHJlbiBsw6Rzc3Qgc2ljaCB3ZWRlciBhbSBTdMO8Y2sgbm9jaCBhbSBaZXR0ZWwgZXJrZW5uZW4u',
      rescueTask: 'Schreibt auf, was ein Fossil ohne Fundzettel belegt und was nicht.',
      onSolve: { docs: ['pruefkarte'], items: [{ id: 'pruefkarte', label: 'Prüfkarte Fundkontext', text: '1. Wo wurde es gefunden? 2. In welcher Schicht, und passt sie zum Profil? 3. Passt das Gestein zur Schicht?' }],
        message: { from: 'kemal', text: 'Nehmt diese Prüfkarte mit. Ihr braucht sie gleich bei den Fundzetteln im Schrank.' }, then: 'r2-1-zettel' } },

    'r2-1-zettel': { id: 'r2-1-zettel', type: 'widerspruch', title: 'Drei Fundzettel',
      prompt: 'Prüft die drei Fundzettel gegen die Profilwand. Tippt im Zettel die Angabe an, die nicht passt, und an der Wand die Stelle, der sie widerspricht.',
      ref: { title: 'Zum Nachschlagen: Prüfkarte', docs: ['pruefkarte'] },
      left: { title: 'Fundzettel', blocks: [
        { title: 'Z1 · Ammonit · Grube Nordhang', items: [{ id: 'z1-schicht', label: 'Schicht 2' }, { id: 'z1-gestein', label: 'brauner Tonstein' }, { id: 'z1-jahr', label: '1974' }] },
        { title: 'Z2 · Fischsaurier-Wirbel · Grube Nordhang', items: [{ id: 'z2-schicht', label: 'Schicht 3' }, { id: 'z2-gestein', label: 'dunkler blättriger Ton' }, { id: 'z2-jahr', label: '1987' }] },
        { title: 'Z3 · Feder-Abdruck · Grube Nordhang', items: [{ id: 'z3-schicht', label: 'Schicht 1' }, { id: 'z3-gestein', label: 'dunkler blättriger Ton' }, { id: 'z3-jahr', label: '1999' }] } ] },
      right: { title: 'Profilwand', blocks: [{ items: [
        { id: 'p1', label: 'Schicht 1 (oben): heller, feinkörniger Plattenkalk' },
        { id: 'p2', label: 'Schicht 2: brauner Tonstein' },
        { id: 'p3', label: 'Schicht 3 (unten): dunkler, blättriger Tonschiefer' },
        { id: 'p4', label: 'Grubensohle, nicht aufgeschlossen' } ] }] },
      hash: ['7c0792fc2869836413dc34d39893e267f4e79ca2ef0316a00f6ae48c4f7b82af', 'fd3856023366fc33857d2973ddd62ba7df3e61ef098f472412881d531fb71bf2'],
      wrongText: 'Nichts passiert. Diese beiden Angaben widersprechen sich nicht.',
      hints: ['Vergleicht bei jedem Zettel Schicht und Gestein mit der Wand.',
              'Welche Schicht ist hell und feinkörnig? Was steht auf dem Zettel?',
              'Z3 nennt Schicht 1, aber ein Gestein, das nur zu Schicht 3 passt.'],
      rescue: 'WmV0dGVsIFozIG5lbm50IFNjaGljaHQgMSwgYmVzY2hyZWlidCBhYmVyIGR1bmtsZW4sIGJsw6R0dHJpZ2VuIFRvbi4gU2NoaWNodCAxIGlzdCBoZWxsZXIgUGxhdHRlbmthbGssIGR1bmtsZXIgVG9uIGdlaMO2cnQgenUgU2NoaWNodCAzLiBTY2hpY2h0IHVuZCBHZXN0ZWluIGF1ZiBkZW0gWmV0dGVsIHdpZGVyc3ByZWNoZW4gc2ljaC4=',
      rescueTask: 'Schreibt auf, woran ihr einen Fundzettel gegen das Profil prüft.',
      onSolve: { text: 'Das ist ein Widerspruch. Kemal steckt eine Nadel an Zettel Z3.', then: 'r2-1-folge' } },

    'r2-1-folge': { id: 'r2-1-folge', type: 'pick', count: 1, title: 'Was folgt daraus?',
      prompt: 'Zettel Z3 passt nicht zur Wand. Wählt, was daraus folgt.',
      cards: [
        { id: 'a', label: 'Der Zettel ist falsch oder das Stück wurde vertauscht. Die Herkunft ist unklar.' },
        { id: 'b', label: 'Das Stück stammt sicher aus Schicht 3.' },
        { id: 'c', label: 'Das Stück ist eine Fälschung.' }
      ],
      hash: '1d3b3480ca6f6648401a74e6a2621471f45db0e4ba5073a5269c8d949bb1c255',
      wrongText: 'Vorsicht. Ein falscher Zettel macht die Herkunft unklar. Er sagt nicht, warum.',
      hints: ['Was wisst ihr sicher: dass etwas nicht passt, oder warum es nicht passt?',
              'Kann man aus einem falschen Zettel ablesen, woher das Stück wirklich kommt?',
              'Sicher ist nur: Die Herkunft ist unklar (a).'],
      rescue: 'QXVzIGVpbmVtIFpldHRlbCwgZGVyIG5pY2h0IHp1bSBQcm9maWwgcGFzc3QsIGZvbGd0IG51cjogRGllIEhlcmt1bmZ0IGlzdCB1bmtsYXIuIE9iIGRlciBaZXR0ZWwgdmVydGF1c2NodCB3dXJkZSBvZGVyIG9iIGplbWFuZCBnZXTDpHVzY2h0IGhhdCwgemVpZ3QgZXIgbmljaHQu',
      rescueTask: 'Schreibt auf, warum ein falscher Zettel noch keine Fälschung beweist.',
      onSolve: { merksatz: 'Ein Fossil ist erst mit seinem Fundkontext ein Befund. Fundort, Schicht und Gestein zeigen, was es belegen kann und was nicht.',
        message: { from: 'kemal', text: 'An der Wand hängt jetzt ein Zettel: „Z3: Herkunft unklar“.\n\nMerkt euch diesen Weg. Ihr braucht ihn wieder.' } } },

    'r2-1-luecken': { id: 'r2-1-luecken', type: 'freetext', minLength: 80, title: 'Warum es so wenige Fossilien gibt (Bonus)',
      prompt: 'Erklärt, warum von den meisten Lebewesen kein Fossil erhalten ist. Nennt zwei Gründe.',
      placeholder: 'Von den meisten Lebewesen bleibt kein Fossil, weil …',
      onSolve: { message: { from: 'kemal', text: 'Fehlende Fossilien sagen nichts gegen die Evolution. Sie zeigen, wie selten die Bedingungen sind.' } } },

    /* ---------------- Mission 2.2 ---------------- */
    'r2-2-kriterium': { id: 'r2-2-kriterium', type: 'pick', count: 1, title: 'Wonach vergleichen?',
      prompt: 'Ihr sollt prüfen, ob drei Tiere miteinander verwandt sein könnten. Wählt das Kriterium, nach dem ihr vergleicht.',
      cards: [
        { id: 'a', label: 'Bau von Skelett und Federn: Merkmale, die auf gemeinsame Vorfahren hindeuten können.' },
        { id: 'b', label: 'Körpergröße der Tiere.' },
        { id: 'c', label: 'Farbe des Gesteins, in dem sie liegen.' },
        { id: 'd', label: 'Wo sie ausgestellt sind.' }
      ],
      hash: '844f826ef7c4d077861e6c4c146013d94c6cc582a58e3a14c060084e311d1bd6',
      wrongText: 'Nichts passiert. Verwandtschaft zeigt sich an Merkmalen des Körpers, nicht am Zufall der Lage.',
      hints: ['Woran erkennt ihr, dass zwei Tiere denselben Ursprung haben könnten?',
              'Was vererbt sich: die Größe oder der Bau?',
              'Es geht um Skelett- und Federmerkmale.'],
      rescue: 'RsO8ciBWZXJ3YW5kdHNjaGFmdCB2ZXJnbGVpY2h0IG1hbiBkZW4gQmF1IHZvbiBTa2VsZXR0IHVuZCBGZWRlcm4uIEdyw7bDn2UsIEdlc3RlaW5zZmFyYmUgdW5kIEF1c3N0ZWxsdW5nc29ydCBzYWdlbiBkYXLDvGJlciBuaWNodHMu',
      rescueTask: 'Schreibt auf, warum Körpergröße als Kriterium für Verwandtschaft nicht reicht.',
      onSolve: { text: 'Der Schrank öffnet sich. Drei Vergleichsstücke und drei Fotokarten liegen auf dem Tisch.', then: 'r2-2-vergleich' } },

    'r2-2-vergleich': { id: 'r2-2-vergleich', type: 'paper', title: 'Der Vergleich',
      ref: { title: 'Zum Nachschlagen: die Fotokarten', docs: ['fk-compsognathus', 'fk-archaeopteryx', 'fk-taube'] },
      prompt: 'Vergleicht die drei Tiere nach eurem Kriterium. Tragt im Logbuch für jedes Merkmal ein: ja, nein oder nicht nachgewiesen.',
      paperTask: 'Vergleicht Compsognathus, Archaeopteryx und Taube an den Stücken auf dem Tisch. Tragt in die Tabelle im Logbuch für jedes der fünf Merkmale ein: ja, nein oder nicht nachgewiesen. Notiert, woran ihr es erkannt habt.',
      doneText: 'Wir haben die Tabelle im Logbuch ausgefüllt.',
      onSolve: { then: 'r2-2-tabelle' } },

    'r2-2-tabelle': { id: 'r2-2-tabelle', type: 'tabelle', title: 'Die Schublade mit dem Urvogel',
      prompt: 'Die Schublade öffnet sich nur, wenn euer Vergleich stimmt. Tippt jede Zelle an, bis euer Ergebnis dasteht.',
      rows: [{ id: 'zaehne', label: 'Zähne' }, { id: 'krallen', label: 'Krallen an den Fingern' }, { id: 'schwanz', label: 'Lange knöcherne Schwanzwirbelsäule' },
             { id: 'federn', label: 'Schwungfedern (Abdrücke)' }, { id: 'brustbein', label: 'Brustbeinkamm' }],
      cols: [{ id: 'compsognathus', label: 'Compsognathus' }, { id: 'archaeopteryx', label: 'Archaeopteryx' }, { id: 'taube', label: 'Taube' }],
      states: [{ id: 'j', label: 'ja' }, { id: 'n', label: 'nein' }, { id: 'x', label: 'nicht nachgewiesen' }],
      colHash: { compsognathus: 'e6e1761d3475e6f47101760cc7b7d2a4abbcbb9b9001d0aef7d107199fddcecc', archaeopteryx: '6546654eb670137a26cc78b2f738d1a9139f9a53e13216d4f411c46dc0379d35', taube: 'eca9b19edcf9f6a7fa18eb81d9caae1422451bf0ff5355e7a573ee06ebb8fcc5' },
      hash: 'd6409e01c8b8a4a0e9b8f7f01f0ec0f30a7c797c3556b583f11d7469cc61fdeb',
      wrongText: 'Nichts passiert. Ein Fossil kann ein Merkmal gehabt haben, das nicht erhalten ist.',
      hints: ['Prüft jede Zelle an den Objekten auf dem Tisch.',
              'Wenn etwas beim Fossil nicht zu sehen ist: Fehlt es wirklich, oder ist es nicht erhalten?',
              'Bei Fossilien steht „nein“ nur, wenn ihr sicher wisst, dass es fehlt. Sonst „nicht nachgewiesen“.'],
      rescue: 'Q29tcHNvZ25hdGh1czogWsOkaG5lIGphLCBLcmFsbGVuIGphLCBTY2h3YW56IGphLCBTY2h3dW5nZmVkZXJuIG5pY2h0IG5hY2hnZXdpZXNlbiwgQnJ1c3RiZWlua2FtbSBuaWNodCBuYWNoZ2V3aWVzZW4uIEFyY2hhZW9wdGVyeXg6IFrDpGhuZSBqYSwgS3JhbGxlbiBqYSwgU2Nod2FueiBqYSwgU2Nod3VuZ2ZlZGVybiBqYSwgQnJ1c3RiZWlua2FtbSBuaWNodCBuYWNoZ2V3aWVzZW4uIFRhdWJlOiBaw6RobmUgbmVpbiwgS3JhbGxlbiBuZWluLCBTY2h3YW56IG5laW4sIFNjaHd1bmdmZWRlcm4gamEsIEJydXN0YmVpbmthbW0gamEu',
      rescueTask: 'Erklärt in eigenen Worten den Unterschied zwischen „nein“ und „nicht nachgewiesen“.',
      onSolve: { docs: ['protokoll'], merksatz: 'Ein Vergleich braucht ein Kriterium, das man vorher festlegt. „Nicht nachgewiesen“ heißt nicht „nicht vorhanden“.',
        text: 'Die Schublade mit dem Urvogel springt auf. Euer Vergleichsprotokoll liegt jetzt in der Akte.' } },

    'r2-2-passung': { id: 'r2-2-passung', type: 'freetext', minLength: 80, title: 'Gehören die Teile zusammen? (Bonus)',
      prompt: 'Der Vergleich nach Merkmalen sagt nicht, ob Körperteile zum selben Tier gehören. Nennt eine Größe, die ihr messen könntet, um das zu prüfen.',
      placeholder: 'Wir würden messen, …' },

    /* ---------------- Mission 2.3 ---------------- */
    'r2-3-mosaik': { id: 'r2-3-mosaik', type: 'objekt', mode: 'markieren', title: 'Der Urvogel unter der Glashaube',
      ref: { title: 'Zum Nachschlagen: Vergleichsprotokoll', docs: ['protokoll'] },
      prompt: 'Untersucht den Urvogel. Tippt jede umrandete Stelle an und markiert sie als ursprünglich oder abgeleitet. Wo das Fossil nichts zeigt, markiert ihr nichts.',
      image: 'bilder/urvogel.jpg', imageAlt: 'Fossil eines Urvogels mit Federn, Zähnen, Krallen und langem Schwanz',
      startText: 'Tippt auf eine umrandete Stelle am Urvogel.',
      pens: [{ id: 'urs', label: 'ursprünglich', tag: 'ursprünglich' }, { id: 'abg', label: 'abgeleitet', tag: 'abgeleitet' }],
      spots: [
        { id: 'zaehne', label: 'Zähne', x: 53, y: 26, w: 8, h: 6, text: 'Spitze Zähne im Kiefer.' },
        { id: 'krallen', label: 'Fingerkrallen', x: 33, y: 16, w: 9, h: 10, text: 'Drei Finger mit Krallen am Flügel.' },
        { id: 'schwanz', label: 'Schwanz', x: 25, y: 58, w: 14, h: 16, text: 'Eine lange Schwanzwirbelsäule aus vielen Wirbeln.' },
        { id: 'federn', label: 'Federn', x: 66, y: 34, w: 22, h: 14, text: 'Abdrücke von Schwungfedern am Flügel.' },
        { id: 'brustbein', label: 'Brustbein', x: 45, y: 39, w: 8, h: 7, text: 'Im Fund nicht erhalten. Ob es einen Brustbeinkamm gab, ist nicht zu erkennen.' }
      ],
      note: 'Ursprünglich: gibt es auch beim Raubdinosaurier. Abgeleitet: typisch für heutige Vögel. Was unmarkiert bleibt: Dazu ist keine Aussage möglich.',
      parts: [{ id: 'urs', label: 'Ursprünglich', hash: '8c143f321ab3a65a33749fa0ac5598fa325cd41a240b0609cdf181d6419723e4' }, { id: 'abg', label: 'Abgeleitet', hash: 'cda564a039e0837f1787519af20aa0a5589c94b179c11ed149e1d83a48c3e4dc' }],
      hash: '71b59472546aa08253c86a97829059bf3900d13a71e4b263110a0e18ee92cf11',
      button: 'Markierungen prüfen',
      wrongText: 'Nichts passiert. „Ursprünglich“ meint: Das Merkmal gab es schon bei den Verwandten.',
      hints: ['Schaut auf euer Protokoll: Welche Merkmale hat der Raubdinosaurier auch?',
              'Eins der Merkmale steht bei Urvogel und Raubdinosaurier auf „nicht nachgewiesen“. Was kann man dazu sagen?',
              'Zähne, Krallen und Schwanz hat auch der Raubdinosaurier. Schwungfedern hat er nach dem Protokoll nicht nachgewiesen, die Taube hat sie. Beim Brustbein lässt sich nichts sagen.'],
      rescue: 'VXJzcHLDvG5nbGljaCAoYXVjaCBiZWltIFJhdWJkaW5vc2F1cmllcik6IFrDpGhuZSwgRmluZ2Vya3JhbGxlbiwgbGFuZ2UgU2Nod2FuendpcmJlbHPDpHVsZS4gQWJnZWxlaXRldCAodHlwaXNjaCBmw7xyIGhldXRpZ2UgVsO2Z2VsKTogU2Nod3VuZ2ZlZGVybi4gWnVtIEJydXN0YmVpbiBpc3Qga2VpbmUgQXVzc2FnZSBtw7ZnbGljaCwgZXMgaXN0IG5pY2h0IGVyaGFsdGVuLg==',
      rescueTask: 'Erklärt in eigenen Worten, was „ursprünglich“ und „abgeleitet“ bedeuten.',
      onSolve: { text: 'An der Wand erscheint ein Diagramm: links der Raubdinosaurier, rechts die Taube, in der Mitte der Urvogel. Linien verbinden gleiche Merkmale.', then: 'r2-3-deutung' } },

    'r2-3-deutung': { id: 'r2-3-deutung', type: 'pick', count: 1, title: 'Was folgt aus dem Mosaik?',
      prompt: 'Wählt die Aussage, die aus der Merkmalskombination folgt.',
      cards: [
        { id: 'a', label: 'Der Urvogel vereint Merkmale zweier Gruppen. Das spricht dafür, dass Raubdinosaurier und Vögel gemeinsame Vorfahren haben.' },
        { id: 'b', label: 'Der Urvogel ist der direkte Vorfahr aller heutigen Vögel.' },
        { id: 'c', label: 'Der Urvogel ist das fehlende Glied, das die Evolution beweist.' },
        { id: 'd', label: 'Der Urvogel hat sich im Lauf seines Lebens vom Dinosaurier zum Vogel verwandelt.' }
      ],
      hash: '3ad1d4ba4af64ba03278a909bc84b8a1b6696964e2d70b55bf83a999f5872baf',
      wrongText: 'Nichts passiert. Eine Kombination von Merkmalen zeigt Verwandtschaft, keine Abstammungslinie.',
      hints: ['Was zeigt das Diagramm an der Wand: eine Linie oder ein Netz von Ähnlichkeiten?',
              'Kann man aus Merkmalen allein sagen, wer wessen Kind war?',
              'Aus Merkmalen folgt Verwandtschaft, nicht eine einzelne Ahnenreihe.'],
      rescue: 'RGllIE1lcmttYWxza29tYmluYXRpb24gc3ByaWNodCBmw7xyIGdlbWVpbnNhbWUgVm9yZmFocmVuIHZvbiBSYXViZGlub3NhdXJpZXJuIHVuZCBWw7ZnZWxuLiBEYXNzIGRlciBVcnZvZ2VsIGRlciBkaXJla3RlIFZvcmZhaHIgb2RlciBkYXMg4oCeZmVobGVuZGUgR2xpZWTigJwgaXN0LCBmb2xndCBkYXJhdXMgbmljaHQuIEVpbiBlaW56ZWxuZXMgVGllciB2ZXJ3YW5kZWx0IHNpY2ggbmljaHQgaW0gTGF1ZiBzZWluZXMgTGViZW5zLg==',
      rescueTask: 'Beschreibt in einem Satz, warum „Bindeglied“ ein schwieriger Begriff ist.',
      onSolve: { merksatz: 'Ein Brückentier zeigt eine Kombination ursprünglicher und abgeleiteter Merkmale. Es ist kein direkter Vorfahr und kein „fehlendes Glied“.',
        evidence: { id: 'ev-2-urvogel', title: 'Der echte Urvogel', text: 'Ein Merkmalsmosaik in einem Stück Stein: ursprüngliche Merkmale (Zähne, Krallen, Schwanz) und ein abgeleitetes (Federn).' },
        message: { from: 'kemal', text: 'Auf Dr. Wendts Arbeitstisch wartet jemand. Ein Sammler will euch etwas zeigen.' } } },

    'r2-3-frage': { id: 'r2-3-frage', type: 'nachfragen', from: 'sammler', title: 'Ein Sammler bietet etwas an',
      prompt: 'Ein Sammler bietet ein Fossil mit Zähnen, Krallen und Federn an. Fragt nach, worauf sich jede Aussage stützt, und ordnet sie ein.',
      askLabel: 'Nachfragen: „Woher wissen Sie das?“',
      optionsTitle: 'Worauf stützt sich die Aussage?',
      selectLabel: 'Stützt sich auf: ', selectPlaceholder: '… einordnen …', selectAria: 'Einordnung für ',
      missingText: 'Ordnet zuerst jede Aussage ein.', button: 'Einordnung prüfen', shuffleOptions: true,
      options: [
        { id: 'sicht', label: 'Am Fund sichtbar' },
        { id: 'anderes', label: 'Sichtbar, aber auf einem anderen Stück' },
        { id: 'deutung', label: 'Deutung, die voraussetzt, dass alle Teile zum selben Tier gehören' },
        { id: 'aussage', label: 'Nur eine Aussage, am Fund nicht prüfbar' }
      ],
      rows: [
        { id: 'h1', say: '„Die Federn sieht man deutlich.“', reply: 'Auf der großen Platte, ja. Schauen Sie selbst.' },
        { id: 'h2', say: '„Zähne und Krallen hat er auch.“', reply: 'Die sind auf der kleinen Platte. Die habe ich ein Jahr später aus derselben Gegend bekommen.' },
        { id: 'h3', say: '„Es ist also ein Brückentier.“', reply: 'Zähne, Krallen, Federn. Was wollen Sie mehr?' },
        { id: 'h4', say: '„Er stammt aus dem Solnhofener Kalk.“', reply: 'Das hat mir der Verkäufer gesagt. Ein Zettel war nicht dabei.' }
      ],
      hash: '4672e7dc7cea55c6aa64532e7e45480e771ba9f1a83beb7f42e9861663aa4a9e',
      wrongText: 'Nichts passiert. Fragt nach: Woher stammt jedes Teil?',
      hints: ['Fragt bei jeder Aussage nach.',
              'Liegt alles in einem Stück Stein?',
              'Federn: sichtbar. Zähne und Krallen: auf einem anderen Stück. „Brückentier“: eine Deutung. Der Fundort: nur eine Aussage.'],
      rescue: 'RGllIEZlZGVybiBzaW5kIGFtIEZ1bmQgc2ljaHRiYXIuIFrDpGhuZSB1bmQgS3JhbGxlbiBsaWVnZW4gYXVmIGVpbmVtIGFuZGVyZW4gU3TDvGNrLiDigJ5CcsO8Y2tlbnRpZXLigJwgaXN0IGVpbmUgRGV1dHVuZywgZGllIHZvcmF1c3NldHp0LCBkYXNzIGFsbGUgVGVpbGUgenUgZWluZW0gVGllciBnZWjDtnJlbi4gRGVyIEZ1bmRvcnQgaXN0IG51ciBlaW5lIEF1c3NhZ2UgZGVzIFNhbW1sZXJzLg==',
      rescueTask: 'Schreibt auf, warum die Frage nach der Zusammengehörigkeit wichtig ist.',
      onSolve: { message: { from: 'kemal', text: 'Bevor jemand „Brückentier“ sagt, muss eine Frage geklärt sein: Gehören alle Teile zum selben Tier?\n\nGenau das prüfen wir beim Berolinavis.' } } },

    'r2-3-kein-brueckentier': { id: 'r2-3-kein-brueckentier', type: 'freetext', minLength: 80, title: 'Wann ist ein Mosaik kein Brückentier? (Bonus)',
      prompt: 'Nennt zwei Möglichkeiten, wann ein Merkmalsmosaik in einem Stein kein Hinweis auf ein Brückentier ist.',
      placeholder: 'Ein Mosaik ist kein Hinweis, wenn …' },

    /* ---------------- Mission 2.4 ---------------- */
    'r2-4-zettel': { id: 'r2-4-zettel', type: 'widerspruch', title: 'Der Fundzettel des Berolinavis',
      prompt: 'Prüft den Fundzettel des Berolinavis mit eurer Prüfkarte gegen das Grabungsprofil. Tippt die beiden Angaben an, die sich widersprechen.',
      ref: { title: 'Zum Nachschlagen: Prüfkarte', docs: ['pruefkarte'] },
      left: { title: 'Fundzettel', blocks: [{ title: 'Berolinavis', items: [
        { id: 'z-ort', label: 'Grube Nordhang' }, { id: 'z-meter', label: 'Meter 14 der Abbauwand' }, { id: 'z-schicht', label: 'Schicht 1' }, { id: 'z-jahr', label: '2019' } ] }] },
      right: { title: 'Grabungsprofil (Spieldaten)', blocks: [{ items: [
        { id: 'g1', label: 'Meter 0 bis 30: Schicht 1 ist abgetragen, oben liegt Schicht 2.' },
        { id: 'g2', label: 'Ab Meter 30: Schicht 1 (heller Plattenkalk) über Schicht 2 und 3.' },
        { id: 'g3', label: 'Grubensohle, nicht aufgeschlossen.' } ] }] },
      hash: ['8ddcd8177cd13c0f92cdf48feb82fc511ff56e09dd44ed04f949137444d59d8c', '96f65245f988ae1ba9aed3b122544b805fc0bd0343bdc7540792e539ea967769'],
      wrongText: 'Nichts passiert. Diese beiden Angaben widersprechen sich nicht.',
      hints: ['Nehmt die Prüfkarte: Wo gefunden? In welcher Schicht?',
              'Gibt es Schicht 1 bei Meter 14?',
              'Bei Meter 14 ist Schicht 1 abgetragen. Der Zettel nennt aber Schicht 1.'],
      rescue: 'RGVyIFpldHRlbCBuZW5udCBNZXRlciAxNCB1bmQgU2NoaWNodCAxLiBMYXV0IEdyYWJ1bmdzcHJvZmlsIGlzdCBTY2hpY2h0IDEgendpc2NoZW4gTWV0ZXIgMCB1bmQgMzAgYWJnZXRyYWdlbi4gRnVuZHN0ZWxsZSB1bmQgU2NoaWNodCBhdWYgZGVtIFpldHRlbCBwYXNzZW4gbmljaHQgenVzYW1tZW4u',
      rescueTask: 'Schreibt auf, welche Angabe des Zettels nicht zum Profil passt und was daraus folgt.',
      onSolve: { evidence: { id: 'ev-2a', title: 'Evidenzkarte A · Fundkontext', text: 'Zettel und Profil passen nicht zusammen.' },
        text: 'Das ist ein Widerspruch. Evidenzkarte A liegt in der Akte.', then: 'r2-4-linien' } },

    'r2-4-linien': { id: 'r2-4-linien', type: 'objekt', mode: 'markieren', partBy: 'tool', title: 'Der Berolinavis',
      ref: { title: 'Zum Nachschlagen: Vergleichstiere und Prüfkarte', docs: ['vergleichstiere', 'pruefkarte'] },
      prompt: 'Untersucht den Berolinavis mit allen Werkzeugen. Markiert jede Stelle, die nicht zu einem Tier in einem Stück Stein passt.',
      image: 'bilder/berolinavis.svg', imageAlt: 'Der Berolinavis auf einer Steinplatte (Platzhalter)',
      startText: 'Wählt ein Werkzeug und tippt auf eine markierte Stelle.',
      tools: [{ id: 'gestein', label: 'Gesteinsansicht' }, { id: 'mess', label: 'Messschieber' }, { id: 'ct', label: 'CT' }, { id: 'lupe', label: 'Lupe' }],
      views: { gestein: 'bilder/berolinavis-gestein.svg', mess: 'bilder/berolinavis-mess.svg', ct: 'bilder/berolinavis-ct.svg', lupe: 'bilder/berolinavis-lupe.svg' },
      pens: [{ id: 'pn', label: 'Passt nicht', tag: 'passt nicht' }],
      spots: [
        { id: 'naht', label: 'Grenze Rumpf/Schwanz', tool: 'gestein', x: 61, y: 15, w: 9, h: 70, text: 'Rumpf in hellem, feinkörnigem Kalk. Schwanz in dunklem, blättrigem Ton mit kleinen Muscheln. Die Grenze läuft quer zur Schichtung.' },
        { id: 'riss', label: 'Riss im Rumpf', tool: 'gestein', x: 24, y: 61, w: 29, h: 10, text: 'Ein feiner Riss im Rumpf, parallel zur Schichtung.' },
        { id: 'wirbel', label: 'Wirbel am Becken', tool: 'mess', x: 57, y: 57, w: 15, h: 17, text: 'Letzter Beckenwirbel 4 mm breit, erster Schwanzwirbel 9 mm. Vergleicht mit den Vergleichstieren.' },
        { id: 'arm', label: 'Arm', tool: 'mess', x: 25, y: 22, w: 9, h: 22, text: 'Oberarm und Unterarm: Längen wie bei den Vergleichstieren.' },
        { id: 'fuell', label: 'Grenze im CT', tool: 'ct', x: 61, y: 15, w: 9, h: 70, text: 'An der Grenze zwischen Rumpf und Schwanz liegt eine Schicht mit geringerer Dichte.' },
        { id: 'riefen', label: 'Krallen', tool: 'lupe', x: 23, y: 15, w: 9, h: 11, text: 'An den Krallen feine, parallele Riefen, alle in dieselbe Richtung.' },
        { id: 'federn', label: 'Federn', tool: 'lupe', x: 34, y: 25, w: 12, h: 15, text: 'Federabdrücke am Arm, fein erhalten.' },
        { id: 'zaehne', label: 'Zähne', tool: 'lupe', x: 12, y: 40, w: 8, h: 8, text: 'Kleine, spitze Zähne im Kiefer.' }
      ],
      note: 'Was unmarkiert bleibt, passt zu einem Tier in einem Stück Stein.',
      parts: [{ id: 'gestein', label: 'Gesteinsansicht', hash: '494f76e2b70a32e54416eae8c153cdb187e37692498efa3fdc9d82f4f004ec5c' }, { id: 'mess', label: 'Messschieber', hash: '8216c57f2fd93c489269481be26880ac9be5f1feab58aac315daf5987ce60c45' },
              { id: 'ct', label: 'CT', hash: '4eab61bf211fae98b02f0baeac678001845366dd7e7bb7a7787709b4f05e55a1' }, { id: 'lupe', label: 'Lupe', hash: 'fd8a5441dcbd432518b64e12d0879842ee0bb1627ba4956bebef254f54434c95' }],
      hash: '4dc78f60c43c69558dc4c9e0a08b7a48a2dad0e9c8247f8e00b3e0094e778666',
      button: 'Markierungen prüfen',
      wrongText: 'Nichts passiert. Mindestens eine Markierung passt nicht.',
      hints: ['Schaltet jedes Werkzeug ein. Was wäre bei einem Tier in einem Stein anders?',
              'Ein natürlicher Riss läuft mit den Schichten. Läuft die Grenze zwischen Rumpf und Schwanz auch so? Und passen die Wirbel zu den Vergleichstieren?',
              'Auffällig sind die Gesteinsgrenze quer zur Schichtung, die Wirbelbreiten, die Füllmasse im CT und die gleichgerichteten Riefen.'],
      rescue: 'R2VzdGVpbnNhbnNpY2h0OiBSdW1wZiB1bmQgU2Nod2FueiBsaWVnZW4gaW4gdmVyc2NoaWVkZW5lbiBHZXN0ZWluZW4sIGRpZSBHcmVuemUgbMOkdWZ0IHF1ZXIgenVyIFNjaGljaHR1bmcgKExpbmllIEIpLiBNZXNzc2NoaWViZXI6IERpZSBXaXJiZWwgcGFzc2VuIG5pY2h0IHp1c2FtbWVuLCBkYXMgVmVyaMOkbHRuaXMgMCw0NCBsaWVndCB3ZWl0IGF1w59lcmhhbGIgZGVyIFZlcmdsZWljaHN0aWVyZSAoTGluaWUgQykuIENUIHVuZCBMdXBlOiBGw7xsbG1hc3NlIGFuIGRlciBHcmVuemUgdW5kIFdlcmt6ZXVnc3B1cmVuIGFuIGRlbiBLcmFsbGVuIChMaW5pZSBEKS4gUmlzcywgQXJtLCBGZWRlcm4gdW5kIFrDpGhuZSBzaW5kIHVuYXVmZsOkbGxpZy4=',
      rescueTask: 'Schreibt zu jeder Linie einen Satz: Was zeigt der Befund? Was zeigt er nicht?',
      onSolve: { evidence: [
          { id: 'ev-2b', title: 'Evidenzkarte B · Gestein', text: 'Körper und Schwanz liegen in verschiedenen Gesteinen, die Grenze verläuft quer zur Schichtung.' },
          { id: 'ev-2c', title: 'Evidenzkarte C · Anatomie', text: 'Die Wirbelbreiten von Becken und Schwanz passen nicht zusammen, weit außerhalb der Vergleichstiere.' },
          { id: 'ev-2d', title: 'Evidenzkarte D · Bearbeitungsspuren', text: 'An der Grenze liegt Füllmasse, die Krallen tragen Werkzeugspuren.' } ],
        message: { from: 'hallmann', text: 'Jeder Fund hat seine Eigenheiten, meine Damen und Herren.' }, then: 'r2-4-ausreden' } },

    'r2-4-ausreden': { id: 'r2-4-ausreden', type: 'nachfragen', from: 'hallmann', title: 'Hallmanns Erklärungen',
      ref: { title: 'Zum Nachschlagen: eure Evidenzkarten', text: 'A: Zettel und Profil passen nicht zusammen.\nB: zwei Gesteine, Grenze quer zur Schichtung.\nC: Wirbelbreiten weit außerhalb der Vergleichstiere.\nD: Füllmasse an der Grenze, Werkzeugspuren an den Krallen.' },
      prompt: 'Hallmann hat zu jedem Befund eine Erklärung. Fragt nach, ob sie auch die anderen Befunde erklärt, und wählt, warum sie nicht reicht.',
      askLabel: 'Nachfragen: „Erklärt das auch die anderen Befunde?“',
      optionsTitle: 'Warum reicht die Erklärung nicht?',
      selectLabel: 'Reicht nicht, weil: ', selectPlaceholder: '… wählen …', selectAria: 'Begründung für ',
      missingText: 'Wählt zuerst für jede Erklärung eine Begründung.', button: 'Begründungen prüfen', shuffleOptions: true,
      options: [
        { id: 'w1', label: 'Erklärt den Zettel, aber nicht die zwei Gesteine im Stück.' },
        { id: 'w2', label: 'Natürliche Schichtgrenzen verlaufen parallel zur Schichtung, nicht quer.' },
        { id: 'w3', label: 'Variabilität erklärt Unterschiede von wenigen Prozent, nicht die doppelte Breite.' },
        { id: 'w4', label: 'Präparation entfernt Gestein. Sie fügt keine Füllmasse ein.' },
        { id: 'w5', label: 'Hallmann lügt.' },
        { id: 'w6', label: 'Ausreden sind in der Wissenschaft nicht erlaubt.' }
      ],
      rows: [
        { id: 'x1', say: 'A · „Der Zettel wurde beim Umlagern vertauscht.“', reply: 'Ein Versehen beim Umlagern. Was hat ein Zettel mit dem Gestein zu tun?' },
        { id: 'x2', say: 'B · „Die Platte lag genau auf der Schichtgrenze.“', reply: 'Schichtgrenzen gibt es in jeder Grube. Mit dem CT hat das nichts zu tun.' },
        { id: 'x3', say: 'C · „Tiere unterscheiden sich eben. Das ist Variabilität.“', reply: 'Das ist doch Ihre eigene Lehre, oder?' },
        { id: 'x4', say: 'D · „Fossilien müssen präpariert werden. Das ist normal.“', reply: 'Fragen Sie jeden Präparator.' }
      ],
      hash: 'd9bd55f96e8e59ebe3035e4b2b3c1332365bc7fcdde9763e06d330bf726d098e',
      wrongText: 'Nichts passiert. Es geht darum, was die Befunde zeigen, nicht um eine Person.',
      hints: ['Welche Erklärung passt zu welchem Befund? Lest jede noch einmal.',
              'Hängen die vier Befunde voneinander ab? Oder kann jeder für sich stimmen?',
              'Jede Ausrede erklärt nur ihren eigenen Befund, und selbst den nicht ganz.'],
      rescue: 'RGVyIHZlcnRhdXNjaHRlIFpldHRlbCBlcmtsw6RydCBuaWNodCBkaWUgendlaSBHZXN0ZWluZS4gTmF0w7xybGljaGUgU2NoaWNodGdyZW56ZW4gbGF1ZmVuIHBhcmFsbGVsIHp1ciBTY2hpY2h0dW5nLCBuaWNodCBxdWVyLiBWYXJpYWJpbGl0w6R0IGVya2zDpHJ0IGtsZWluZSBVbnRlcnNjaGllZGUsIG5pY2h0IGRpZSBkb3BwZWx0ZSBXaXJiZWxicmVpdGUuIFByw6RwYXJhdGlvbiBlbnRmZXJudCBHZXN0ZWluLCBzaWUgZsO8Z3Qga2VpbmUgRsO8bGxtYXNzZSBlaW4u',
      rescueTask: 'Erklärt, warum vier unabhängige Befunde stärker sind als ein einzelner.',
      onSolve: { message: { from: 'kemal', text: 'Ich bin Präparator. Präparieren nimmt Stein weg. Es klebt nichts zusammen.\n\nAuf den Evidenzkarten steht jetzt: „Ausrede erklärt nur diesen Befund.“ Das Schloss am Arbeitstisch wartet.' } } },

    'r2-4-schloss': { id: 'r2-4-schloss', type: 'cloze', triple: true, title: 'Das Schloss verlangt einen gesicherten Satz',
      prompt: 'Vervollständigt den Satz. Das Schloss prüft alle Lücken gemeinsam.',
      parts: [{ strong: 'Aussage: ' }, 'Der Befund spricht dafür, dass der Berolinavis ', { gap: 'g1', label: 'Lücke 1' }, ' ist.', { nl: true },
        { strong: 'Beleg: ' }, { gap: 'g2', label: 'Lücke 2', block: true }, { nl: true },
        { strong: 'Reichweite: ' }, 'Das ist ', { gap: 'g3', label: 'Lücke 3', block: true }, { nl: true },
        { strong: 'Offen: ' }, 'Ob Hallmann davon wusste, ist ', { gap: 'g4', label: 'Lücke 4' }, '.'],
      gaps: {
        g1: [{ id: 'a', label: 'aus verschiedenen Teilen zusammengesetzt' }, { id: 'b', label: 'ein ganz normal erhaltenes Tier' }, { id: 'c', label: 'sicher gefälscht' }],
        g2: [{ id: 'a', label: 'Vier voneinander unabhängige Befunde zeigen dasselbe.' }, { id: 'b', label: 'Hallmanns Aussagen zeigen es.' }, { id: 'c', label: 'Ein besonders auffälliger Befund zeigt es.' }],
        g3: [{ id: 'a', label: 'ein starker Verdacht, das Urteil folgt mit allen Beweisen.' }, { id: 'b', label: 'ein bewiesener Betrug.' }, { id: 'c', label: 'eine Frage des Geschmacks.' }],
        g4: [{ id: 'a', label: 'noch offen' }, { id: 'b', label: 'bewiesen' }, { id: 'c', label: 'unwichtig' }]
      },
      tripleText: 'Das Schloss bleibt zu. Mindestens eine Lücke stimmt nicht. Lest den Satz laut und prüft jede Lücke einzeln.',
      traps: [
        { g: 'g3', v: 'b', from: 'kemal', text: 'Vorsicht. Wir haben gezeigt, dass er zusammengesetzt ist, nicht wer es getan hat.' },
        { g: 'g4', v: 'b', from: 'kemal', text: 'Vorsicht. Wir haben gezeigt, dass er zusammengesetzt ist, nicht wer es getan hat.' },
        { g: 'g1', v: 'c', from: 'kemal', text: '„Sicher“ ist zu stark. Wir haben einen Verdacht, kein Urteil.' },
        { g: 'g2', v: 'c', from: 'kemal', text: 'Ein einzelner Befund lässt sich harmlos erklären. Was ist stärker?' },
        { g: 'g2', v: 'b', from: 'kemal', text: 'Was jemand sagt, ist kein Befund.' }
      ],
      hash: '512588fd8ec0f10ee05b6ee927e3a0ccc745a616fb355f15477f760807695293',
      hints: ['Lest den Satz Teil für Teil. Was haben wir gezeigt, was nicht?',
              'Haben wir gezeigt, wer den Berolinavis so gemacht hat?',
              'Zusammengesetzt, vier unabhängige Befunde, starker Verdacht, Vorsatz noch offen.'],
      rescue: 'RGVyIEJlZnVuZCBzcHJpY2h0IGRhZsO8ciwgZGFzcyBkZXIgQmVyb2xpbmF2aXMgYXVzIHZlcnNjaGllZGVuZW4gVGVpbGVuIHp1c2FtbWVuZ2VzZXR6dCBpc3QuIEJlbGVnOiBWaWVyIHZvbmVpbmFuZGVyIHVuYWJow6RuZ2lnZSBCZWZ1bmRlIHplaWdlbiBkYXNzZWxiZS4gUmVpY2h3ZWl0ZTogRGFzIGlzdCBlaW4gc3RhcmtlciBWZXJkYWNodCwgZGFzIFVydGVpbCBmb2xndCBtaXQgYWxsZW4gQmV3ZWlzZW4uIE9mZmVuOiBPYiBIYWxsbWFubiBkYXZvbiB3dXNzdGUsIGlzdCBub2NoIG9mZmVuLg==',
      rescueTask: 'Schreibt den Satz in euren Worten ins Logbuch.',
      onSolve: {
        fx: 'lock', fxTitle: 'Schloss 2 geöffnet', fxText: 'Aussage, Beleg und Reichweite halten. Der Befund ist zusammengesetzt.',
        evidence: { id: 'ev-2', title: 'Beweisakte Teil 2 · Der Befund ist zusammengesetzt', text: 'Vier voneinander unabhängige Befunde sprechen dafür, dass der Berolinavis zusammengesetzt ist. Das ist ein starker Verdacht, noch kein Urteil.' },
        merksatz: 'Ein einzelner Befund kann harmlos erklärt werden. Erst mehrere voneinander unabhängige Befunde, die dasselbe zeigen, tragen ein Urteil. Ein Verdacht ist kein Beweis.',
        message: { from: 'wendt', text: 'Damit haben wir einen starken Verdacht. Aber ein Verdacht ist kein Urteil.\n\n– J. W.' },
        message2: { from: 'hallmann', text: 'Eine Verwerfung hat die beiden Gesteine zusammengeschoben. So etwas kommt vor, meine Damen und Herren.' } } },

    'r2-4-verwerfung': { id: 'r2-4-verwerfung', type: 'freetext', minLength: 100, title: 'Hallmanns Verwerfung (Bonus)',
      ref: { title: 'Zum Nachschlagen: eure Evidenzkarten', text: 'B: zwei Gesteine, Grenze quer zur Schichtung.\nD: Füllmasse an der Grenze, Werkzeugspuren an den Krallen.' },
      prompt: 'Hallmann sagt nun: „Eine Verwerfung hat die beiden Gesteine zusammengeschoben.“ Beurteilt, welche Befunde diese Erklärung stützen würden und welche dagegen sprechen.',
      placeholder: 'Für eine Verwerfung spräche …, dagegen spricht …' }
  }
});
